Feature/yo matrix
ihmcrobotics/ihmc-yovariables pull request #10
Opened 2024-03-14 18:54 UTC by james-p-foster

Adds `YoMatrix` and associated tests. Consolidates implementations from `scs2-simulation` and `ihmc-robotics-toolkit`.

2024-03-29 16:16 UTC, SylvainBertrand requested changes
I'm good when javadoc is in

2024-03-29 16:16 UTC, SylvainBertrand commented on src/main/java/us/ihmc/yoVariables/math/YoMatrix.java
Missing the javadoc

2024-04-01 14:21 UTC, james-p-foster commented on src/main/java/us/ihmc/yoVariables/math/YoMatrix.java
Added javadoc for most user-facing methods

2024-04-01 19:34 UTC, SylvainBertrand approved these changes

2024-04-01 19:46 UTC, merged